import js from "@eslint/js";
import tseslint from "typescript-eslint";
import importPlugin from "eslint-plugin-import";
import reactHooks from "eslint-plugin-react-hooks";

/**
 * Flat config. The point of this file is not style — there is no formatter here — but to turn the
 * prose in `.claude/rules/` into gates that fail:
 *
 *   ARCH-1  -> import/no-restricted-paths zones (checked on RESOLVED paths, so the `~/*` alias
 *              cannot be used to sneak around a layer boundary)
 *   ARCH-2  -> no framework/driver imports in domain (no-restricted-imports)
 *   DIR-6   -> no `index.ts` barrels
 *   DIR-7   -> cross-layer imports must use `~/*`, never a relative escape
 */

/** The four layers, innermost first. A layer may not import from anything to its right. */
const OUTWARD = {
  domain: ["application", "infrastructure", "presentation"],
  application: ["infrastructure", "presentation"],
  infrastructure: ["presentation"],
};

/** DIR-7: a relative specifier that names another layer has escaped its own. */
const RELATIVE_LAYER_ESCAPE = ["domain", "application", "infrastructure", "presentation"].flatMap(
  (layer) => [`../${layer}/**`, `../**/${layer}/**`],
);

const BARREL = {
  group: ["**/index", "**/index.js", "**/index.ts"],
  message: "DIR-6: no index.ts barrels — import the module directly.",
};

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "graphify-out/**",
      "drizzle/**",
      "build/out/**",
      ".output/**",
      ".vinxi/**",
      // Generated by the TanStack route plugin (DIR-5).
      "src/presentation/routeTree.gen.ts",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // ---- shared: import hygiene + the DIR rules -------------------------------------------------
  {
    files: ["**/*.{ts,tsx}"],
    plugins: { import: importPlugin },
    settings: {
      "import/resolver": {
        typescript: {
          alwaysTryTypes: true,
          // Two real tsconfigs by design: the NodeNext backend gate and the bundler/DOM
          // presentation gate. Both must be consulted so `~/*` and `@/*` resolve.
          project: ["./tsconfig.json", "./src/presentation/tsconfig.json"],
          noWarnOnMultipleProjects: true,
        },
      },
    },
    rules: {
      "import/no-unresolved": "error",
      "import/no-useless-path-segments": ["error", { noUselessIndex: true }],
      "import/no-cycle": ["error", { maxDepth: Infinity }],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "separate-type-imports" },
      ],
      // Unused args/vars are allowed when explicitly discarded with a leading underscore
      // (the destructured `_userId`/`_senseId` in the Drizzle upsert path).
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },

  // ---- ARCH-1: the dependency rule, on resolved paths ------------------------------------------
  {
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "import/no-restricted-paths": [
        "error",
        {
          zones: Object.entries(OUTWARD).flatMap(([target, forbidden]) =>
            forbidden.map((from) => ({
              target: `./src/${target}`,
              from: `./src/${from}`,
              message: `ARCH-1: ${target} must not import ${from} — dependencies point inward only.`,
            })),
          ),
        },
      ],
      "no-restricted-imports": ["error", { patterns: [BARREL, ...restrictedRelative()] }],
    },
  },

  // ---- ARCH-2 / ARCH-3: the domain stays pure --------------------------------------------------
  {
    files: ["src/domain/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            BARREL,
            ...restrictedRelative(),
            {
              group: [
                "react",
                "react-*",
                "@tanstack/*",
                "drizzle-orm",
                "drizzle-orm/*",
                "@neondatabase/*",
                "@electric-sql/*",
                "better-auth",
                "better-auth/*",
                "ts-fsrs",
                "wink-*",
              ],
              message:
                "ARCH-1/ARCH-3: the domain imports no framework, driver or library — put it behind a port.",
            },
          ],
        },
      ],
      // The domain does no I/O (ARCH-2).
      "no-restricted-globals": [
        "error",
        { name: "fetch", message: "ARCH-2: the domain performs no I/O." },
      ],
    },
  },

  // ---- presentation ---------------------------------------------------------------------------
  {
    files: ["src/presentation/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },

  // ---- tests + the build pipeline --------------------------------------------------------------
  {
    files: ["**/*.test.ts", "**/*.test.tsx", "src/infrastructure/test*.ts"],
    rules: {
      // Test doubles legitimately widen types at the boundary.
      "@typescript-eslint/no-explicit-any": "off",
      // ARCH-1 governs SOURCE dependencies. A use-case test composes the real adapters it will run
      // against — pglite, FakeJudge — which is this repo's whole test strategy (no in-memory doubles).
      // Forbidding that would only push the wiring into a helper and hide it.
      "import/no-restricted-paths": "off",
    },
  },
  {
    files: ["build/**/*.ts", "*.config.ts", "*.config.js", "vitest.setup.ts"],
    rules: {
      "no-restricted-imports": "off",
      "import/no-restricted-paths": "off",
    },
  },
);

/** DIR-7: ban relative specifiers that cross a layer boundary; `~/*` is the way across. */
function restrictedRelative() {
  return [
    {
      group: RELATIVE_LAYER_ESCAPE,
      message: "DIR-7: cross-layer imports use the `~/*` alias, not a relative escape.",
    },
  ];
}
